# 变异系数法
变异系数的计算很简单，就是用标准差除以平均值。变异系数越大，则数据的偏离程度越大。
变异系数法的思想中，某个指标偏离程度越大，说明该指标越难以实现，因此它是反映所评对象差距的关键指标，应被赋予更高的权重。

In [1]:
import pandas as pd
import os
os.chdir(r'C:\Users\7LStar\Desktop\study\python\《Python电商数据分析实战：从电商实际案例出发洞悉数据分析全流程》随书数据源及代码\相关数据源\第9章 行业机会分析和权重确定\相关数据')

In [2]:
result=pd.DataFrame()
for name in os.listdir():
    df=pd.read_excel(name)
    df['年份']=df['日期'].str[:4]
    df['销售额']=df['访客数']*df['转化率']*df['客单价']
    result=pd.concat([result,df])
result.head()

        日期     品牌    访客数       转化率   客单价 三级类目         详细类目    年份           销售额
0  2023-12  品牌-14   9348  0.060899   134   冰爪  专项户外运动装备&冰爪  2023  76284.024818
1  2023-12  品牌-20   1187  0.047991  1244   冰爪  专项户外运动装备&冰爪  2023  70864.932081
2  2023-12   品牌-4  10433  0.049205    97   冰爪  专项户外运动装备&冰爪  2023  49795.124129
3  2023-12  品牌-13   4648  0.024492   428   冰爪  专项户外运动装备&冰爪  2023  48722.984375
4  2023-12  品牌-18   3977  0.057258    71   冰爪  专项户外运动装备&冰爪  2023  16167.851684

In [4]:
#年度客单价=年度销售额/年度购买人数
result['购买人数']=result['访客数']*result['转化率']
pd.set_option('display.float_format',lambda x:'%.2f'%x)#浮点数显示两位小数
#按年度汇总
item_gp=result.groupby(['详细类目','年份'])['销售额','购买人数'].sum().reset_index()
item_gp.head()

C:\Users\7LStar\AppData\Local\Temp\ipykernel_35248\1765393438.py:5: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  item_gp=result.groupby(['详细类目','年份'])['销售额','购买人数'].sum().reset_index()

               详细类目    年份         销售额      购买人数
0       专项户外运动装备&冰爪  2022  7884578.41 103174.19
1       专项户外运动装备&冰爪  2023 30163749.95 310832.84
2  专项户外运动装备&呼吸管-呼吸器  2022  7173132.43  66854.25
3  专项户外运动装备&呼吸管-呼吸器  2023 17198793.49 136986.67
4      专项户外运动装备&安全带  2022 19393866.43 133751.10

In [22]:
item_gp['客单价']=item_gp['销售额']/item_gp['购买人数']
item_gp=item_gp[item_gp['年份']=='2023']
item_gp.head()

               详细类目    年份         销售额      购买人数     客单价
1       专项户外运动装备&冰爪  2023 30163749.95 310832.84   97.04
3  专项户外运动装备&呼吸管-呼吸器  2023 17198793.49 136986.67  125.55
5      专项户外运动装备&安全带  2023 66140160.84 303756.40  217.74
7      专项户外运动装备&救生衣  2023 98807893.65 445640.13  221.72
9       专项户外运动装备&气瓶  2023 36317479.97  33514.51 1083.63

In [9]:
result1=pd.DataFrame()
for name in os.listdir():
    df=pd.read_excel(name)
    df['年份']=df['日期'].str[:4]
    df['销售额']=df['访客数']*df['转化率']*df['客单价']
    df_sum=df.groupby('年份')['销售额'].sum().reset_index()
    df_sum['类目']=name.replace('.xlsx','')
    result1=pd.concat([result1,df_sum])
result1.head()

     年份         销售额                类目
0  2022  7884578.41       专项户外运动装备&冰爪
1  2023 30163749.95       专项户外运动装备&冰爪
0  2022  7173132.43  专项户外运动装备&呼吸管-呼吸器
1  2023 17198793.49  专项户外运动装备&呼吸管-呼吸器
0  2022 19393866.43      专项户外运动装备&安全带

In [12]:
final=pd.pivot_table(result1,index='类目',columns='年份',values='销售额',aggfunc='sum').reset_index()
final.columns=['类目','2022年销售额','2023年销售额']

                      类目     2022年销售额     2023年销售额
0            专项户外运动装备&冰爪   7884578.41  30163749.95
1       专项户外运动装备&呼吸管-呼吸器   7173132.43  17198793.49
2           专项户外运动装备&安全带  19393866.43  66140160.84
3           专项户外运动装备&救生衣  23820417.15  98807893.65
4            专项户外运动装备&气瓶   8052409.00  36317479.97
..                   ...          ...          ...
123         防护-救生装备&防护面罩   3464970.97  11843236.83
124      防潮垫-地席-枕头&地布-地席   3828998.31  12738643.79
125         防潮垫-地席-枕头&枕头  52704583.51 214983856.48
126        防潮垫-地席-枕头&防潮垫  64294811.64 260637588.07
127  防潮垫-地席-枕头&防潮垫-地席-枕头 114956693.58 434554583.83

[128 rows x 3 columns]

In [13]:
final['销售增速']=(final['2023年销售额']-final['2022年销售额'])/final['2022年销售额']
final.head()

                 类目    2022年销售额    2023年销售额  销售增速
0       专项户外运动装备&冰爪  7884578.41 30163749.95  2.83
1  专项户外运动装备&呼吸管-呼吸器  7173132.43 17198793.49  1.40
2      专项户外运动装备&安全带 19393866.43 66140160.84  2.41
3      专项户外运动装备&救生衣 23820417.15 98807893.65  3.15
4       专项户外运动装备&气瓶  8052409.00 36317479.97  3.51

In [14]:
final['大类目']=final['类目'].str.split('&').str[0]
final['细分类目']=final['类目'].str.split('&').str[1]
final.head()

                 类目    2022年销售额    2023年销售额  销售增速       大类目     细分类目
0       专项户外运动装备&冰爪  7884578.41 30163749.95  2.83  专项户外运动装备       冰爪
1  专项户外运动装备&呼吸管-呼吸器  7173132.43 17198793.49  1.40  专项户外运动装备  呼吸管-呼吸器
2      专项户外运动装备&安全带 19393866.43 66140160.84  2.41  专项户外运动装备      安全带
3      专项户外运动装备&救生衣 23820417.15 98807893.65  3.15  专项户外运动装备      救生衣
4       专项户外运动装备&气瓶  8052409.00 36317479.97  3.51  专项户外运动装备       气瓶

In [16]:
r=final.sort_values(['大类目','销售增速'],ascending=False)
r.head()

                      类目     2022年销售额     2023年销售额  销售增速        大类目       细分类目
125         防潮垫-地席-枕头&枕头  52704583.51 214983856.48  3.08  防潮垫-地席-枕头         枕头
126        防潮垫-地席-枕头&防潮垫  64294811.64 260637588.07  3.05  防潮垫-地席-枕头        防潮垫
127  防潮垫-地席-枕头&防潮垫-地席-枕头 114956693.58 434554583.83  2.78  防潮垫-地席-枕头  防潮垫-地席-枕头
124      防潮垫-地席-枕头&地布-地席   3828998.31  12738643.79  2.33  防潮垫-地席-枕头      地布-地席
122      防护-救生装备&防护-救生装备 103906995.09 516112688.85  3.97    防护-救生装备    防护-救生装备

In [17]:
r.groupby('大类目').head(1)

,类目,2022年销售额,2023年销售额,销售增速,大类目,细分类目
125,防潮垫-地席-枕头&枕头,52704583.51,214983856.48,3.08,防潮垫-地席-枕头,枕头
122,防护-救生装备&防护-救生装备,103906995.09,516112688.85,3.97,防护-救生装备,防护-救生装备
115,睡袋&睡袋,193959076.88,594014206.98,2.06,睡袋,睡袋
114,登山杖-手杖&登山杖-手杖,77763133.79,295317365.32,2.80,登山杖-手杖,登山杖-手杖
113,洗漱清洁-护理用品&防虫-防蚊用品,23484997.36,75632462.16,2.22,洗漱清洁-护理用品,防虫-防蚊用品
111,望远镜-夜视仪-户外眼镜&望远镜-夜视仪-户外眼镜,220271388.35,1025433112.52,3.66,望远镜-夜视仪-户外眼镜,望远镜-夜视仪-户外眼镜
106,旅行便携装备&晾衣绳,4306504.60,18455947.82,3.29,旅行便携装备,晾衣绳
99,户外鞋靴&滑雪鞋-雪地靴,79046497.00,364683981.78,3.61,户外鞋靴,滑雪鞋-雪地靴
91,户外照明&营地灯-帐篷灯,21839003.61,104666693.76,3.79,户外照明,营地灯-帐篷灯
68,户外服装&抓绒衣,101650296.49,454712444.95,3.47,户外服装,抓绒衣
52,户外休闲家具&户外桌椅套装,14235575.41,66832433.35,3.69,户外休闲家具,户外桌椅套装
45,垂钓装备&鱼钩,55895341.31,299165733.63,4.35,垂钓装备,鱼钩
4,专项户外运动装备&气瓶,8052409.00,36317479.97,3.51,专项户外运动装备,气瓶

In [23]:
#合并表
final_new=pd.merge(final,item_gp,left_on='类目',right_on='详细类目',how='inner')
final_new.head()

,类目,2022年销售额,2023年销售额,销售增速,大类目,细分类目,详细类目,年份,销售额,购买人数,客单价
0,专项户外运动装备&冰爪,7884578.41,30163749.95,2.83,专项户外运动装备,冰爪,专项户外运动装备&冰爪,2023,30163749.95,310832.84,97.04
1,专项户外运动装备&呼吸管-呼吸器,7173132.43,17198793.49,1.40,专项户外运动装备,呼吸管-呼吸器,专项户外运动装备&呼吸管-呼吸器,2023,17198793.49,136986.67,125.55
2,专项户外运动装备&安全带,19393866.43,66140160.84,2.41,专项户外运动装备,安全带,专项户外运动装备&安全带,2023,66140160.84,303756.40,217.74
3,专项户外运动装备&救生衣,23820417.15,98807893.65,3.15,专项户外运动装备,救生衣,专项户外运动装备&救生衣,2023,98807893.65,445640.13,221.72
4,专项户外运动装备&气瓶,8052409.00,36317479.97,3.51,专项户外运动装备,气瓶,专项户外运动装备&气瓶,2023,36317479.97,33514.51,1083.63

In [24]:
final_new=final_new[['类目','2022年销售额','2023年销售额','销售增速','客单价']]
final_new.head()

                 类目    2022年销售额    2023年销售额  销售增速     客单价
0       专项户外运动装备&冰爪  7884578.41 30163749.95  2.83   97.04
1  专项户外运动装备&呼吸管-呼吸器  7173132.43 17198793.49  1.40  125.55
2      专项户外运动装备&安全带 19393866.43 66140160.84  2.41  217.74
3      专项户外运动装备&救生衣 23820417.15 98807893.65  3.15  221.72
4       专项户外运动装备&气瓶  8052409.00 36317479.97  3.51 1083.63

In [26]:
final_new.describe()

           2022年销售额      2023年销售额   销售增速     客单价
count        128.00        128.00 128.00  128.00
mean   105009765.18  389253544.32   2.79  245.77
std    231216148.93  863806475.71   0.61  251.62
min       589492.92    2094447.84   1.40   18.37
25%      8931205.15   32890176.12   2.40   77.96
50%     27727218.81  113122708.51   2.80  153.08
75%     90346726.97  371512115.05   3.20  321.37
max   1535788007.33 6578928834.59   4.35 1615.38

In [29]:
#计算变异系数，取出标准差和平均数
cov=final_new.describe().T[['mean','std']]
cov

                 mean          std
2022年销售额 105009765.18 231216148.93
2023年销售额 389253544.32 863806475.71
销售增速             2.79         0.61
客单价            245.77       251.62

In [30]:
cov['cov']=cov['std']/cov['mean']
cov['cov_percent']=cov['cov']/cov['cov'].sum()
cov

                 mean          std  cov  cov_percent
2022年销售额 105009765.18 231216148.93 2.20         0.39
2023年销售额 389253544.32 863806475.71 2.22         0.39
销售增速             2.79         0.61 0.22         0.04
客单价            245.77       251.62 1.02         0.18

#数据标准化
最大最小值归一化法，它的计算公式为（对应列某个值-列最小值）/（列最大值
列最小值）。该公式把对应列所有的值都压缩在0～1的范围内，让数据单位保持一致。

In [31]:
#每一个指标都套用了上面的去量纲公式
final_new['2022_mms'] = (final_new['2022年销售额'] - final_new['2022年销售额'].min())/(final_new['2022年销售额'].max() - final_new['2022年销售额'].min())
final_new['2023_mms'] = (final_new['2023年销售额'] - final_new['2023年销售额'].min())/(final_new['2023年销售额'].max() - final_new['2023年销售额'].min())
final_new['销售增速_mms'] = (final_new['销售增速'] - final_new['销售增速'].min())/(final_new['销售增速'].max() - final_new['销售增速'].min())
final_new['客单价_mms'] = (final_new['客单价'] - final_new['客单价'].min())/(final_new['客单价'].max() - final_new['客单价'].min()) 

#按2023年销售额排序，查看前5条结果
final_new.sort_values('2023年销售额',ascending = False).head()

,类目,2022年销售额,2023年销售额,销售增速,客单价,2022_mms,2023_mms,销售增速_mms,客单价_mms
67,户外服装&户外服装,1535788007.33,6578928834.59,3.28,405.94,1.00,1.00,0.64,0.24
17,垂钓装备&垂钓装备,1263322207.67,4530217246.31,2.59,107.43,0.82,0.69,0.40,0.06
95,户外鞋靴&户外鞋靴,1174675113.88,3554767358.42,2.03,423.33,0.76,0.54,0.21,0.25
31,垂钓装备&钓竿,666732975.43,3053970690.23,3.58,293.47,0.43,0.46,0.74,0.17
58,户外服装&冲锋衣,913619579.64,2826169162.98,2.09,557.40,0.59,0.43,0.24,0.34

In [34]:
#综合发展指数
final_new['综合发展指数']=final_new['2022_mms']*0.39+final_new['2023_mms']*0.39+final_new['销售增速_mms']*0.04+final_new['客单价_mms']*0.18
final_new.sort_values('综合发展指数',ascending=False)[['类目','2022年销售额','2023年销售额','销售增速','客单价','综合发展指数']].head(10)

               类目      2022年销售额      2023年销售额  销售增速     客单价  综合发展指数
67      户外服装&户外服装 1535788007.33 6578928834.59  3.28  405.94    0.85
17      垂钓装备&垂钓装备 1263322207.67 4530217246.31  2.59  107.43    0.62
95      户外鞋靴&户外鞋靴 1174675113.88 3554767358.42  2.03  423.33    0.56
58       户外服装&冲锋衣  913619579.64 2826169162.98  2.09  557.40    0.47
74       户外服装&羽绒衣  512927562.77 1994130010.74  2.89 1615.38    0.45
31        垂钓装备&钓竿  666732975.43 3053970690.23  3.58  293.47    0.41
100  户外鞋靴&登山鞋-徒步鞋  572466499.39 1630094311.28  1.85  634.04    0.32
77    户外服装&运动户外风衣  399289508.04 1311388238.25  2.28  220.13    0.21
94     户外鞋靴&户外休闲鞋  276639321.46  744078859.06  1.69  739.48    0.20
43       垂钓装备&鱼线轮  205590742.05  955452386.15  3.65  434.42    0.19